# Generated by Django 2.1.15 on 2020-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200116_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
