# Generated by Django 2.1.15 on 2020-01-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200116_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='VAT',
            new_name='vat',
        ),
    ]
