# Generated by Django 2.1.15 on 2020-01-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200119_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
